### ISSUE TITLE
Feature request: checked_pow

### ISSUE THREAD

**Issue by rscarson** [mamrhein/fpdec.rs#10]
To exponentiate fixed-p values I currently have to drop both operands to float first, checked_pow would round out the available set of checked operators

**Comment by mamrhein** [comment]
For which kind of application do you need exponentiation?
Would integer exponents be sufficient?

**Comment by rscarson** [comment]
I would prefer like-type exponentiation if possible

**Comment by mamrhein** [comment]
As stated in the README, `fpdec` is targeted at typical business applications, dealing with numbers representing quantities, money and the like, not at scientific computations. For this kind of applications I can't see a demand for exponentiation.
This is the reason I asked why you need it.

**Comment by rscarson** [comment]
Fair enough. I am using it in the creation of a parser - I was just trying to implement my exponentiation operator for decimal literals

**Comment by mamrhein** [comment]
Calculating a correctly rounded result for exponentiation with fractional exponents is not an easy task.
I fear I don't have the capacity to tackle that in the near future.

**Comment by rscarson** [comment]
Would you be open to the following method for calculating this? - below is the implementation I am using 
I can open a PR if it looks workable:

I am using the taylor series to approximate the result of `a**b == e**(b * ln(a))`:

```rust
    /// Type-same checked exponentiation for fixed-point decimals
    pub fn checked_pow(&self, exp: &Self) -> Option<Self> {
        //
        // First we handle the edge cases of exp <= 0
        if exp == &Fixed::zero() {
            // x**0 == 1
            return Some(Fixed::one());
        } else if exp < &Fixed::zero() {
            // x**-n == 1 / x**n
            let exp = Dec!(-1) * *exp.inner().clone();
            let inverse = self.checked_pow(&exp.into())?;
            let result = Fixed::one() / inverse;
            return result.ok();
        }

        //
        // To calculate a**b, we can use the fact that a**b == e**(b * ln(a))
        let a = *self.inner().clone();
        let b = *exp.inner().clone();

        //
        // Approximate ln(a) using the taylor series for ln(x) = (x-1) - (x-1)**2/2 + (x-1)**3/3 - [...]
        let a_s1 = a.checked_sub(Dec!(1))?;
        let mut ln_a_mul = a_s1.clone();
        let mut ln_a = a_s1.clone();
        let mut multiplier = Dec!(-1);
        for i in 2..=500 {
            ln_a_mul = ln_a_mul.checked_mul(a_s1)?;
            let factor = ln_a_mul.checked_div(Decimal::from(i))?;
            let factor = factor.checked_mul(multiplier)?;

            ln_a = ln_a.checked_add(factor)?;
            multiplier = multiplier.checked_mul(Dec!(-1))?;
        }

        //
        // santity check - high precision checked_mul can fail, but if we check scale
        // we can avoid panics with unchecked multiplication
        if b.trunc().checked_mul(ln_a.trunc()).is_none() {
            return None;
        }

        //
        // Now, Finally we approximate e**(b * ln(a)) using the taylor series for e**x = 1 + x + x**2/2! + [...]
        let b_ln_a = b * ln_a;
        let mut multiplier = b_ln_a.clone();
        let mut e_b_ln_a = Dec!(1).checked_add(b_ln_a)?;
        let mut divisor = Dec!(1);
        // 34! overflows Decimal so we must stop at 33 rounds
        for i in 2..=33 {
            divisor = divisor.checked_mul(Decimal::from(i))?; // i!
            multiplier *= b_ln_a; // x**i
            let factor = multiplier.checked_div(divisor)?; // x**i / i!
            e_b_ln_a = e_b_ln_a.checked_add(factor)?;
        }

        //
        // Since this is an approximation, we round to the maximum precision of a and b
        let result = e_b_ln_a.round(a.n_frac_digits().max(b.n_frac_digits()) as i8);
        Some(Self::new(BoxedDecimal::from(result)))
    }
    ```

**Comment by mamrhein** [comment]
There are some issues with your implementation.
The most serious: the Taylor series for the natural logarithm that you use only converges in the interval 0 < x <= 2. 
For x = 2.01 it gives (with 500 iterations) ln(x) = 0.842332002294142083 instead of 0,698134722070984383, for x = 2.05 it gives 38403460.305692957670819500 (!) instead of 0,717839793150316810.
For values a bit less than 2 you would need more iterations in order to get a result with an error <= 10^-18. For example:
ln(1.95) gives (with 500 iterations) 0.667829372575662906, the correct value (rounded to 18 fractional digits) would be 0,667829372575655434. The same is true for values near zero: for x = 0.01 it gives -4.604048715848259933 instead of  -4,605170185988091368.
In general, are you really sure that your users want/need logarithms and exponentiation with fractional exponents on fixed-point types? 
And then, converting to an f64 and using f64::ln and f64::exp gives you results with an error <= 10^-15. 
While there are better polynomials to approximate the natural logarithm and one can surely find ways to get correctly rounded results with fpdec::Decimals, I still doubt it's worth the efforts.
P.S: I'm currently working on a library for octuple-precision binary floating-point arithmetics and may get soon to implement ln and exp. Then, maybe I find an easy way to port that to fpdec. But, please, don't take that for granted.

**Comment by rscarson** [comment]
Fair enough
I will return to using float conversion for decimal exponentiation
